// ────────────────────────────────────────────────────────────────────────────
// Benjamin Moore Color Library — 550+ colors across major collections
// ────────────────────────────────────────────────────────────────────────────

export interface BenjaminMooreColor {
  name: string;
  number: string;
  hex: string;
  collection: string;
}

// ── AFFINITY COLLECTION (AF-series) ─────────────────────────────────────────
const affinityColors: BenjaminMooreColor[] = [
  { name: "Frostine", number: "AF-5", hex: "#EFF2EC", collection: "Affinity" },
  { name: "Gardenia", number: "AF-10", hex: "#F4F1EA", collection: "Affinity" },
  { name: "Steam", number: "AF-15", hex: "#F1F0E7", collection: "Affinity" },
  { name: "Mascarpone", number: "AF-20", hex: "#F9F8E9", collection: "Affinity" },
  { name: "Paper", number: "AF-25", hex: "#F1F1E4", collection: "Affinity" },
  { name: "Deep", number: "AF-30", hex: "#EFEDDC", collection: "Affinity" },
  { name: "Vapor", number: "AF-35", hex: "#F0EDE0", collection: "Affinity" },
  { name: "Lychee", number: "AF-40", hex: "#F6EDDD", collection: "Affinity" },
  { name: "Collector's Item", number: "AF-45", hex: "#F2EBDD", collection: "Affinity" },
  { name: "Etiquette", number: "AF-50", hex: "#E6E1D6", collection: "Affinity" },
  { name: "Sonnet", number: "AF-55", hex: "#E4DCCE", collection: "Affinity" },
  { name: "Peau de Soie", number: "AF-60", hex: "#E6DCCF", collection: "Affinity" },
  { name: "Fossil", number: "AF-65", hex: "#E4DECF", collection: "Affinity" },
  { name: "Battenberg", number: "AF-70", hex: "#EAE6D1", collection: "Affinity" },
  { name: "Refined", number: "AF-75", hex: "#DFE0CE", collection: "Affinity" },
  { name: "Jute", number: "AF-80", hex: "#DAD3BF", collection: "Affinity" },
  { name: "Frappe", number: "AF-85", hex: "#E8DCC4", collection: "Affinity" },
  { name: "Harmony", number: "AF-90", hex: "#DECDB2", collection: "Affinity" },
  { name: "Hush", number: "AF-95", hex: "#D5CAB0", collection: "Affinity" },
  { name: "Pashmina", number: "AF-100", hex: "#BCB3A2", collection: "Affinity" },
  { name: "Elk", number: "AF-105", hex: "#988669", collection: "Affinity" },
  { name: "Coriander", number: "AF-110", hex: "#958166", collection: "Affinity" },
  { name: "Lodge", number: "AF-115", hex: "#7E674E", collection: "Affinity" },
  { name: "Tamarind", number: "AF-120", hex: "#746147", collection: "Affinity" },
  { name: "Morrel", number: "AF-125", hex: "#B39779", collection: "Affinity" },
  { name: "Truffle", number: "AF-130", hex: "#C7B198", collection: "Affinity" },
  { name: "Interlude", number: "AF-135", hex: "#B9A38B", collection: "Affinity" },
  { name: "Pensive", number: "AF-140", hex: "#BEAB96", collection: "Affinity" },
  { name: "Kangaroo", number: "AF-145", hex: "#C0B299", collection: "Affinity" },
  { name: "Cotswold", number: "AF-150", hex: "#B6A796", collection: "Affinity" },
  { name: "Weimaraner", number: "AF-155", hex: "#A09383", collection: "Affinity" },
  { name: "Carob", number: "AF-160", hex: "#8D705E", collection: "Affinity" },
  { name: "Kona", number: "AF-165", hex: "#735742", collection: "Affinity" },
  { name: "French Press", number: "AF-170", hex: "#604E44", collection: "Affinity" },
  { name: "Barista", number: "AF-175", hex: "#59433B", collection: "Affinity" },
  { name: "Wenge", number: "AF-180", hex: "#3D2E2C", collection: "Affinity" },
  { name: "Venetian", number: "AF-185", hex: "#C5AA97", collection: "Affinity" },
  { name: "Boudoir", number: "AF-190", hex: "#DBC3AF", collection: "Affinity" },
  { name: "Terra", number: "AF-195", hex: "#DEBFA0", collection: "Affinity" },
  { name: "Lingerie", number: "AF-200", hex: "#D5B696", collection: "Affinity" },
  { name: "Serendipity", number: "AF-205", hex: "#DAB192", collection: "Affinity" },
  { name: "Milk and Honey", number: "AF-210", hex: "#D4A583", collection: "Affinity" },
  { name: "Italianate", number: "AF-215", hex: "#CC9A77", collection: "Affinity" },
  { name: "Masada", number: "AF-220", hex: "#A4683F", collection: "Affinity" },
  { name: "Firenze", number: "AF-225", hex: "#B97551", collection: "Affinity" },
  { name: "Buttered Bread", number: "AF-230", hex: "#C47641", collection: "Affinity" },
  { name: "Warmed", number: "AF-235", hex: "#975B3B", collection: "Affinity" },
  { name: "Satchel", number: "AF-240", hex: "#815032", collection: "Affinity" },
  { name: "Ipanema", number: "AF-245", hex: "#C6A48D", collection: "Affinity" },
  { name: "Head Start", number: "AF-250", hex: "#F0DFD3", collection: "Affinity" },
  { name: "Fondant", number: "AF-255", hex: "#F9EEE4", collection: "Affinity" },
  { name: "Proposal", number: "AF-260", hex: "#E9DAD5", collection: "Affinity" },
  { name: "Charmeuse", number: "AF-265", hex: "#DCCDC3", collection: "Affinity" },
  { name: "Tea Light", number: "AF-270", hex: "#A16F69", collection: "Affinity" },
  { name: "Rustique", number: "AF-275", hex: "#7D3F2F", collection: "Affinity" },
  { name: "Salsa", number: "AF-280", hex: "#AC5540", collection: "Affinity" },
  { name: "Moroccan Red", number: "AF-285", hex: "#B35D51", collection: "Affinity" },
  { name: "Caliente", number: "AF-290", hex: "#8B2829", collection: "Affinity" },
  { name: "Pomegranate", number: "AF-295", hex: "#8C393F", collection: "Affinity" },
  { name: "Dinner Party", number: "AF-300", hex: "#773738", collection: "Affinity" },
  { name: "Ylang Ylang", number: "AF-305", hex: "#F5EACF", collection: "Affinity" },
  { name: "Subtle Touch", number: "AF-310", hex: "#F3E8D0", collection: "Affinity" },
  { name: "Jicama", number: "AF-315", hex: "#F3DFBD", collection: "Affinity" },
  { name: "Flawless", number: "AF-320", hex: "#EEDCBE", collection: "Affinity" },
  { name: "Handmade", number: "AF-325", hex: "#EFD8B3", collection: "Affinity" },
  { name: "Soleil", number: "AF-330", hex: "#FDEABE", collection: "Affinity" },
  { name: "Safari", number: "AF-335", hex: "#EBD3A9", collection: "Affinity" },
  { name: "Oat", number: "AF-340", hex: "#D0BB93", collection: "Affinity" },
  { name: "Honeymoon", number: "AF-345", hex: "#D9BB88", collection: "Affinity" },
  { name: "Kurkuma", number: "AF-350", hex: "#BA9358", collection: "Affinity" },
  { name: "Etruscan", number: "AF-355", hex: "#B08356", collection: "Affinity" },
  { name: "Farm Fresh", number: "AF-360", hex: "#C5A079", collection: "Affinity" },
  { name: "Amulet", number: "AF-365", hex: "#DAC89B", collection: "Affinity" },
  { name: "Citrine", number: "AF-370", hex: "#C9AC6F", collection: "Affinity" },
  { name: "Rattan", number: "AF-375", hex: "#BCA678", collection: "Affinity" },
  { name: "Coastal Fog", number: "AF-380", hex: "#C3B494", collection: "Affinity" },
  { name: "Splendor", number: "AF-385", hex: "#CEBE96", collection: "Affinity" },
  { name: "Glacial", number: "AF-390", hex: "#C4B89E", collection: "Affinity" },
  { name: "Meditation", number: "AF-395", hex: "#ACA48D", collection: "Affinity" },
  { name: "Elemental", number: "AF-400", hex: "#B2AD8E", collection: "Affinity" },
  { name: "Thicket", number: "AF-405", hex: "#A2A17F", collection: "Affinity" },
  { name: "Lapland", number: "AF-410", hex: "#B5AF8F", collection: "Affinity" },
  { name: "Grasshopper", number: "AF-415", hex: "#C6C498", collection: "Affinity" },
  { name: "Agave", number: "AF-420", hex: "#ADAA6F", collection: "Affinity" },
  { name: "Anjou", number: "AF-425", hex: "#C8B77A", collection: "Affinity" },
  { name: "Wasabi", number: "AF-430", hex: "#B5A95D", collection: "Affinity" },
  { name: "Spa", number: "AF-435", hex: "#D6D4B9", collection: "Affinity" },
  { name: "Urban Nature", number: "AF-440", hex: "#B2B697", collection: "Affinity" },
  { name: "Aventurine", number: "AF-445", hex: "#989D79", collection: "Affinity" },
  { name: "Seedling", number: "AF-450", hex: "#A4B793", collection: "Affinity" },
  { name: "Croquet", number: "AF-455", hex: "#B3B7A0", collection: "Affinity" },
  { name: "Jojoba", number: "AF-460", hex: "#868B75", collection: "Affinity" },
  { name: "Wind", number: "AF-465", hex: "#C8CBB7", collection: "Affinity" },
  { name: "Flora", number: "AF-470", hex: "#A4AD9F", collection: "Affinity" },
  { name: "Lush", number: "AF-475", hex: "#748172", collection: "Affinity" },
  { name: "Boreal", number: "AF-480", hex: "#54604F", collection: "Affinity" },
  { name: "Crystalline", number: "AF-485", hex: "#CAD5C9", collection: "Affinity" },
  { name: "Tranquility", number: "AF-490", hex: "#BCC4BC", collection: "Affinity" },
  { name: "Azores", number: "AF-495", hex: "#8AA199", collection: "Affinity" },
  { name: "Atmospheric", number: "AF-500", hex: "#899E9B", collection: "Affinity" },
  { name: "Blue Nile", number: "AF-505", hex: "#6F898E", collection: "Affinity" },
  { name: "Dragonfly", number: "AF-510", hex: "#3E625F", collection: "Affinity" },
  { name: "Exhale", number: "AF-515", hex: "#A0B9C2", collection: "Affinity" },
  { name: "Schooner", number: "AF-520", hex: "#537788", collection: "Affinity" },
  { name: "Fiji", number: "AF-525", hex: "#4F8093", collection: "Affinity" },
  { name: "Lucerne", number: "AF-530", hex: "#3B657E", collection: "Affinity" },
  { name: "Serenata", number: "AF-535", hex: "#ACC2CD", collection: "Affinity" },
  { name: "Constellation", number: "AF-540", hex: "#D6E2E4", collection: "Affinity" },
  { name: "Solitude", number: "AF-545", hex: "#A4AFB5", collection: "Affinity" },
  { name: "Amsterdam", number: "AF-550", hex: "#82959E", collection: "Affinity" },
  { name: "Montpelier", number: "AF-555", hex: "#728188", collection: "Affinity" },
  { name: "Flint", number: "AF-560", hex: "#575D5F", collection: "Affinity" },
  { name: "Mysterious", number: "AF-565", hex: "#464C55", collection: "Affinity" },
  { name: "Coastline", number: "AF-570", hex: "#929EA9", collection: "Affinity" },
  { name: "Instinct", number: "AF-575", hex: "#BBC6D1", collection: "Affinity" },
  { name: "Luxe", number: "AF-580", hex: "#757E93", collection: "Affinity" },
  { name: "Wisteria", number: "AF-585", hex: "#9D9DA7", collection: "Affinity" },
  { name: "Tempest", number: "AF-590", hex: "#7B777F", collection: "Affinity" },
  { name: "Inspired", number: "AF-595", hex: "#AD9FAB", collection: "Affinity" },
  { name: "Amorous", number: "AF-600", hex: "#968997", collection: "Affinity" },
  { name: "Slip", number: "AF-605", hex: "#D7D3D6", collection: "Affinity" },
  { name: "Batik", number: "AF-610", hex: "#CDBAB6", collection: "Affinity" },
  { name: "Violetta", number: "AF-615", hex: "#C5B8BC", collection: "Affinity" },
  { name: "Sanctuary", number: "AF-620", hex: "#B5AAB0", collection: "Affinity" },
  { name: "Aplomb", number: "AF-625", hex: "#95727E", collection: "Affinity" },
  { name: "Kalamata", number: "AF-630", hex: "#705160", collection: "Affinity" },
  { name: "Bonne Nuit", number: "AF-635", hex: "#7D6B74", collection: "Affinity" },
  { name: "Kasbah", number: "AF-640", hex: "#7A6D70", collection: "Affinity" },
  { name: "Chambord", number: "AF-645", hex: "#57474F", collection: "Affinity" },
  { name: "Caponata", number: "AF-650", hex: "#463234", collection: "Affinity" },
  { name: "Silhouette", number: "AF-655", hex: "#58514D", collection: "Affinity" },
  { name: "Granite", number: "AF-660", hex: "#837E7C", collection: "Affinity" },
  { name: "Angelica", number: "AF-665", hex: "#D5CFCC", collection: "Affinity" },
  { name: "Nightingale", number: "AF-670", hex: "#B7B5B3", collection: "Affinity" },
  { name: "Fusion", number: "AF-675", hex: "#A6A3A1", collection: "Affinity" },
  { name: "Wish", number: "AF-680", hex: "#D0CBC3", collection: "Affinity" },
  { name: "Thunder", number: "AF-685", hex: "#BEB9AE", collection: "Affinity" },
  { name: "Metropolitan", number: "AF-690", hex: "#BBBEB9", collection: "Affinity" },
  { name: "Eternity", number: "AF-695", hex: "#BFC3C3", collection: "Affinity" },
  { name: "Storm", number: "AF-700", hex: "#A0A19F", collection: "Affinity" },
  { name: "Cinder", number: "AF-705", hex: "#878684", collection: "Affinity" },
  { name: "Secret", number: "AF-710", hex: "#898A84", collection: "Affinity" },
  { name: "Dolphin", number: "AF-715", hex: "#86847E", collection: "Affinity" },
  { name: "Sparrow", number: "AF-720", hex: "#847D6F", collection: "Affinity" },
];

// ── AMERICAS COLORS (AC-series) ───────────────────────────────────────────────
const americasColors: BenjaminMooreColor[] = [
  { name: "Coastal Plain", number: "AC-1", hex: "#CBC5B1", collection: "Americas Colors" },
  { name: "Berkshire Beige", number: "AC-2", hex: "#B0A690", collection: "Americas Colors" },
  { name: "Texas Leather", number: "AC-3", hex: "#867B69", collection: "Americas Colors" },
  { name: "Yosemite Sand", number: "AC-4", hex: "#DECAAD", collection: "Americas Colors" },
  { name: "Springfield Tan", number: "AC-5", hex: "#C1A888", collection: "Americas Colors" },
  { name: "New England Clay", number: "AC-6", hex: "#A18562", collection: "Americas Colors" },
  { name: "Adobe Beige", number: "AC-7", hex: "#D9C5AC", collection: "Americas Colors" },
  { name: "Butte", number: "AC-8", hex: "#C9AC8C", collection: "Americas Colors" },
  { name: "Nugget", number: "AC-9", hex: "#B7916C", collection: "Americas Colors" },
  { name: "San Juan", number: "AC-10", hex: "#DBB9A2", collection: "Americas Colors" },
  { name: "Sierra Madre", number: "AC-11", hex: "#CBA387", collection: "Americas Colors" },
  { name: "Copper Mountain", number: "AC-12", hex: "#B27E61", collection: "Americas Colors" },
  { name: "Mochachino", number: "AC-13", hex: "#D9BEAE", collection: "Americas Colors" },
  { name: "Pecos River", number: "AC-14", hex: "#C49E88", collection: "Americas Colors" },
  { name: "Colorado Rocky Mountain", number: "AC-15", hex: "#B88D76", collection: "Americas Colors" },
  { name: "Kentucky Haze", number: "AC-16", hex: "#A4B1AF", collection: "Americas Colors" },
  { name: "Sea of Green", number: "AC-17", hex: "#8C9591", collection: "Americas Colors" },
  { name: "Smoky Ash", number: "AC-18", hex: "#7B8580", collection: "Americas Colors" },
  { name: "Homestead", number: "AC-19", hex: "#A5BCB7", collection: "Americas Colors" },
  { name: "Mountain Misty", number: "AC-20", hex: "#758F89", collection: "Americas Colors" },
  { name: "Silver Sage", number: "AC-21", hex: "#5B726A", collection: "Americas Colors" },
  { name: "Nantucket Sound", number: "AC-22", hex: "#A3B5BB", collection: "Americas Colors" },
  { name: "James River Gray", number: "AC-23", hex: "#87999F", collection: "Americas Colors" },
  { name: "Charlotte Slate", number: "AC-24", hex: "#677A80", collection: "Americas Colors" },
  { name: "Harbor Town", number: "AC-25", hex: "#C8C8C3", collection: "Americas Colors" },
  { name: "Ozark Mountains", number: "AC-26", hex: "#B7B5AD", collection: "Americas Colors" },
  { name: "Galveston Gray", number: "AC-27", hex: "#9A968D", collection: "Americas Colors" },
  { name: "Smoke Signals", number: "AC-28", hex: "#C2C0BB", collection: "Americas Colors" },
  { name: "San Diego", number: "AC-29", hex: "#B5B3AF", collection: "Americas Colors" },
  { name: "Winter Gates", number: "AC-30", hex: "#A39E97", collection: "Americas Colors" },
  { name: "Hot Springs", number: "AC-31", hex: "#CABFB0", collection: "Americas Colors" },
  { name: "Pismo Beach", number: "AC-32", hex: "#B8AB9B", collection: "Americas Colors" },
  { name: "Mesa Tan", number: "AC-33", hex: "#A08F7D", collection: "Americas Colors" },
  { name: "Cape Cod Gray", number: "AC-34", hex: "#BFB9AF", collection: "Americas Colors" },
  { name: "Valley Forge Tan", number: "AC-35", hex: "#B7B0A4", collection: "Americas Colors" },
  { name: "Shenandoah Taupe", number: "AC-36", hex: "#A69B8E", collection: "Americas Colors" },
  { name: "Big Sur", number: "AC-37", hex: "#D3C9BE", collection: "Americas Colors" },
  { name: "North Canyon", number: "AC-38", hex: "#C4B9AF", collection: "Americas Colors" },
  { name: "Mt. McKinley", number: "AC-39", hex: "#AA9B8E", collection: "Americas Colors" },
  { name: "Glacier Bay", number: "AC-40", hex: "#EDEBE1", collection: "Americas Colors" },
  { name: "Acadia White", number: "AC-41", hex: "#F3F0E0", collection: "Americas Colors" },
  { name: "Grand Canyon Ivory", number: "AC-42", hex: "#EAE6D1", collection: "Americas Colors" },
];

// ── HISTORICAL COLORS (HC-series) ─────────────────────────────────────────────
const historicalColors: BenjaminMooreColor[] = [
  { name: "Lime White", number: "HC-1", hex: "#F0EAD0", collection: "Historical Colors" },
  { name: "Sutton Place Blue", number: "HC-2", hex: "#A9B7C9", collection: "Historical Colors" },
  { name: "Hawthorne Yellow", number: "HC-4", hex: "#D4AC4C", collection: "Historical Colors" },
  { name: "Cornfield Yellow", number: "HC-6", hex: "#D6C57C", collection: "Historical Colors" },
  { name: "Wyeth Blue", number: "HC-8", hex: "#6B8FAB", collection: "Historical Colors" },
  { name: "Wedgewood Gray", number: "HC-9", hex: "#C5C8D0", collection: "Historical Colors" },
  { name: "Morning Dew White", number: "HC-12", hex: "#E8E4D8", collection: "Historical Colors" },
  { name: "Yellow Buff", number: "HC-14", hex: "#D5BD8B", collection: "Historical Colors" },
  { name: "Sandy Brown", number: "HC-17", hex: "#C8A882", collection: "Historical Colors" },
  { name: "Oxford White", number: "HC-19", hex: "#E8E2D4", collection: "Historical Colors" },
  { name: "Monroe Bisque Light", number: "HC-25", hex: "#E0CDB2", collection: "Historical Colors" },
  { name: "Monroe Bisque", number: "HC-26", hex: "#DBCBAB", collection: "Historical Colors" },
  { name: "Providence Olive", number: "HC-28", hex: "#B0A472", collection: "Historical Colors" },
  { name: "Hathaway Gold", number: "HC-29", hex: "#C8A840", collection: "Historical Colors" },
  { name: "Lenox Tan", number: "HC-30", hex: "#C4AB89", collection: "Historical Colors" },
  { name: "Windham Cream", number: "HC-33", hex: "#E5D8B8", collection: "Historical Colors" },
  { name: "Linen White", number: "HC-35", hex: "#E0D3BC", collection: "Historical Colors" },
  { name: "Quincy Tan", number: "HC-38", hex: "#C2A880", collection: "Historical Colors" },
  { name: "Sandy Hook Grey", number: "HC-41", hex: "#BFC1BC", collection: "Historical Colors" },
  { name: "Gloucester Sage", number: "HC-44", hex: "#9BAF97", collection: "Historical Colors" },
  { name: "Davenport Tan", number: "HC-52", hex: "#C2A87F", collection: "Historical Colors" },
  { name: "Litchfield Gray", number: "HC-55", hex: "#8E8880", collection: "Historical Colors" },
  { name: "Copley Gray", number: "HC-57", hex: "#B2AFA7", collection: "Historical Colors" },
  { name: "Gray Cashmere", number: "HC-59", hex: "#CAC8BB", collection: "Historical Colors" },
  { name: "Chelsea Mauve", number: "HC-60", hex: "#BCA8A8", collection: "Historical Colors" },
  { name: "Plymouth Rock", number: "HC-70", hex: "#C5B49E", collection: "Historical Colors" },
  { name: "Old Salem Gray", number: "HC-74", hex: "#9B9188", collection: "Historical Colors" },
  { name: "Rustic Taupe", number: "HC-78", hex: "#9E8870", collection: "Historical Colors" },
  { name: "Alexandria Beige", number: "HC-82", hex: "#BEA98C", collection: "Historical Colors" },
  { name: "Hampshire Taupe", number: "HC-85", hex: "#A89880", collection: "Historical Colors" },
  { name: "Carrington Beige", number: "HC-91", hex: "#B8A484", collection: "Historical Colors" },
  { name: "Saybrook Sage", number: "HC-95", hex: "#9FAE8E", collection: "Historical Colors" },
  { name: "Mountain Peak White", number: "HC-97", hex: "#EDE9DD", collection: "Historical Colors" },
  { name: "Valley Forge Brown", number: "HC-96", hex: "#95826C", collection: "Historical Colors" },
  { name: "Gettysburg Gray", number: "HC-101", hex: "#B4B0A4", collection: "Historical Colors" },
  { name: "Thornton Sage", number: "HC-107", hex: "#8A9E82", collection: "Historical Colors" },
  { name: "Gloucester Sage Deep", number: "HC-108", hex: "#B5BFB0", collection: "Historical Colors" },
  { name: "Nantucket Gray", number: "HC-111", hex: "#8A9FAA", collection: "Historical Colors" },
  { name: "Homestead Brown", number: "HC-113", hex: "#7B6549", collection: "Historical Colors" },
  { name: "Georgetown Green", number: "HC-114", hex: "#6A8A6A", collection: "Historical Colors" },
  { name: "Georgian Green", number: "HC-115", hex: "#89A285", collection: "Historical Colors" },
  { name: "Guilford Green", number: "HC-116", hex: "#778C6D", collection: "Historical Colors" },
  { name: "Sudbury Green", number: "HC-117", hex: "#6A8460", collection: "Historical Colors" },
  { name: "Portland Green", number: "HC-118", hex: "#587D5A", collection: "Historical Colors" },
  { name: "Chrome Green", number: "HC-119", hex: "#5E7556", collection: "Historical Colors" },
  { name: "Morristown Green", number: "HC-122", hex: "#5E7952", collection: "Historical Colors" },
  { name: "Plantation", number: "HC-125", hex: "#4D6646", collection: "Historical Colors" },
  { name: "Newburyport Slate", number: "HC-126", hex: "#4D5E65", collection: "Historical Colors" },
  { name: "Huntington Green", number: "HC-131", hex: "#57674C", collection: "Historical Colors" },
  { name: "Washington Green", number: "HC-132", hex: "#4E6045", collection: "Historical Colors" },
  { name: "Millbrook", number: "HC-133", hex: "#6E7A52", collection: "Historical Colors" },
  { name: "Tarrytown Green", number: "HC-134", hex: "#5E7148", collection: "Historical Colors" },
  { name: "Fernwood Green", number: "HC-136", hex: "#7E9972", collection: "Historical Colors" },
  { name: "Saguaro Sage", number: "HC-140", hex: "#6B8062", collection: "Historical Colors" },
  { name: "Kennett Square", number: "HC-142", hex: "#647259", collection: "Historical Colors" },
  { name: "Narragansett Green", number: "HC-143", hex: "#4D6258", collection: "Historical Colors" },
  { name: "Buxton Blue", number: "HC-149", hex: "#547A8C", collection: "Historical Colors" },
  { name: "Annapolis Green", number: "HC-150", hex: "#5B836E", collection: "Historical Colors" },
  { name: "Hale Navy", number: "HC-154", hex: "#364958", collection: "Historical Colors" },
  { name: "Newburyport Blue", number: "HC-155", hex: "#3B5A74", collection: "Historical Colors" },
  { name: "Van Deusen Blue", number: "HC-156", hex: "#4A6274", collection: "Historical Colors" },
  { name: "Constitution Blue", number: "HC-157", hex: "#2D4B6A", collection: "Historical Colors" },
  { name: "Hamilton Blue", number: "HC-158", hex: "#3D566A", collection: "Historical Colors" },
  { name: "Jamestown Blue", number: "HC-160", hex: "#5F8596", collection: "Historical Colors" },
  { name: "Yarmouth Blue", number: "HC-162", hex: "#7193A8", collection: "Historical Colors" },
  { name: "Pale Smoke", number: "HC-163", hex: "#C4CBD6", collection: "Historical Colors" },
  { name: "Kendall Charcoal", number: "HC-166", hex: "#737469", collection: "Historical Colors" },
  { name: "Coventry Gray", number: "HC-169", hex: "#9A9FA0", collection: "Historical Colors" },
  { name: "Stonington Gray", number: "HC-170", hex: "#C0C0BA", collection: "Historical Colors" },
  { name: "Revere Pewter", number: "HC-172", hex: "#C2B9A7", collection: "Historical Colors" },
  { name: "Edgecomb Gray", number: "HC-173", hex: "#CBB99B", collection: "Historical Colors" },
  { name: "Pale Oak", number: "HC-174", hex: "#DDD5C4", collection: "Historical Colors" },
  { name: "Sandy Hook Gray", number: "HC-175", hex: "#C3C0B9", collection: "Historical Colors" },
  { name: "Thunder", number: "HC-176", hex: "#717574", collection: "Historical Colors" },
  { name: "Pembroke", number: "HC-177", hex: "#6F7168", collection: "Historical Colors" },
  { name: "Rockport Gray", number: "HC-178", hex: "#74716A", collection: "Historical Colors" },
  { name: "Tate Olive", number: "HC-179", hex: "#878556", collection: "Historical Colors" },
  { name: "Muskoka Hills", number: "HC-65", hex: "#C2B89E", collection: "Historical Colors" },
  { name: "White Asparagus", number: "HC-109", hex: "#C4C4A8", collection: "Historical Colors" },
];

// ── OFF-WHITES (OC-series) ────────────────────────────────────────────────────
const offWhiteColors: BenjaminMooreColor[] = [
  { name: "White", number: "OC-1", hex: "#F5F5F2", collection: "Off-Whites" },
  { name: "Silver White", number: "OC-2", hex: "#F0F0EC", collection: "Off-Whites" },
  { name: "Brilliant White", number: "OC-3", hex: "#F6F6F4", collection: "Off-Whites" },
  { name: "Snowfall White", number: "OC-4", hex: "#F3F2EE", collection: "Off-Whites" },
  { name: "Cloud White", number: "OC-5", hex: "#F4F2EB", collection: "Off-Whites" },
  { name: "Creamy White", number: "OC-7", hex: "#F0EBD8", collection: "Off-Whites" },
  { name: "Antique White", number: "OC-8", hex: "#F2EAD9", collection: "Off-Whites" },
  { name: "Eastern Reflections", number: "OC-9", hex: "#EDE9DD", collection: "Off-Whites" },
  { name: "Dove White", number: "OC-11", hex: "#F2F0E8", collection: "Off-Whites" },
  { name: "Classic White", number: "OC-12", hex: "#F2EFE4", collection: "Off-Whites" },
  { name: "Natural White", number: "OC-14", hex: "#F0EDE2", collection: "Off-Whites" },
  { name: "White Sand", number: "OC-15", hex: "#EDE8DB", collection: "Off-Whites" },
  { name: "Antique White", number: "OC-16", hex: "#F2EAD8", collection: "Off-Whites" },
  { name: "White Dove", number: "OC-17", hex: "#F3F1E9", collection: "Off-Whites" },
  { name: "Ivory Tusk", number: "OC-18", hex: "#EFEAD8", collection: "Off-Whites" },
  { name: "Sea Salt", number: "OC-19", hex: "#D6D2C4", collection: "Off-Whites" },
  { name: "Pale Oak", number: "OC-20", hex: "#DDD5C4", collection: "Off-Whites" },
  { name: "Gentle Cream", number: "OC-21", hex: "#F0E8D4", collection: "Off-Whites" },
  { name: "Intense White", number: "OC-22", hex: "#F0EDE3", collection: "Off-Whites" },
  { name: "Classic Gray", number: "OC-23", hex: "#E3E0D7", collection: "Off-Whites" },
  { name: "White Cloud", number: "OC-24", hex: "#F5F2EA", collection: "Off-Whites" },
  { name: "Breathless", number: "OC-25", hex: "#EEE9DC", collection: "Off-Whites" },
  { name: "White Blush", number: "OC-26", hex: "#F0EBE0", collection: "Off-Whites" },
  { name: "Feather White", number: "OC-28", hex: "#EEE9E0", collection: "Off-Whites" },
  { name: "Cement Gray", number: "OC-30", hex: "#E2DDD4", collection: "Off-Whites" },
  { name: "Distant Gray", number: "OC-36", hex: "#E5E1D8", collection: "Off-Whites" },
  { name: "Grayish Beige", number: "OC-38", hex: "#C4B8A8", collection: "Off-Whites" },
  { name: "Serena", number: "OC-42", hex: "#E0DDD6", collection: "Off-Whites" },
  { name: "Swiss Coffee", number: "OC-45", hex: "#F0EBE0", collection: "Off-Whites" },
  { name: "Seashell", number: "OC-50", hex: "#F1EDE4", collection: "Off-Whites" },
  { name: "Sage", number: "OC-51", hex: "#AABA9E", collection: "Off-Whites" },
  { name: "Gray Owl", number: "OC-52", hex: "#CFD0CA", collection: "Off-Whites" },
  { name: "Paper White", number: "OC-55", hex: "#E0E2DC", collection: "Off-Whites" },
  { name: "White Heron", number: "OC-57", hex: "#F0EDE3", collection: "Off-Whites" },
  { name: "Lincoln White", number: "OC-58", hex: "#EEE9DF", collection: "Off-Whites" },
  { name: "Chantilly Lace", number: "OC-65", hex: "#F5F4EF", collection: "Off-Whites" },
  { name: "Sand Dune", number: "OC-75", hex: "#D4C9B0", collection: "Off-Whites" },
  { name: "Pale Almond", number: "OC-78", hex: "#E8DFCC", collection: "Off-Whites" },
  { name: "White Flour", number: "OC-83", hex: "#F3F0E6", collection: "Off-Whites" },
  { name: "Barley", number: "OC-90", hex: "#C8B08C", collection: "Off-Whites" },
  { name: "Classic Linen", number: "OC-96", hex: "#F0E8D4", collection: "Off-Whites" },
  { name: "Soft Chamois", number: "OC-100", hex: "#E4D8BF", collection: "Off-Whites" },
  { name: "Simply White", number: "OC-17", hex: "#F7F5ED", collection: "Off-Whites" },
  { name: "Atrium White", number: "OC-145", hex: "#F1ECE1", collection: "Off-Whites" },
  { name: "Snowflake", number: "OC-148", hex: "#F2F0EC", collection: "Off-Whites" },
  { name: "Decorator's White", number: "OC-149", hex: "#F4F2EC", collection: "Off-Whites" },
  { name: "Linen White", number: "912", hex: "#F4EFE1", collection: "Off-Whites" },
  { name: "Super White", number: "PM-1", hex: "#F4F4F4", collection: "Off-Whites" },
  { name: "Ivory White", number: "925", hex: "#F0EAD6", collection: "Off-Whites" },
  { name: "Navajo White", number: "958", hex: "#F1E4C4", collection: "Off-Whites" },
];

// ── WILLIAMSBURG COLLECTION (CW-series) ──────────────────────────────────────
const williamsburgColors: BenjaminMooreColor[] = [
  { name: "Palace Arms", number: "CW-5", hex: "#8A6845", collection: "Williamsburg" },
  { name: "Acer", number: "CW-10", hex: "#B07858", collection: "Williamsburg" },
  { name: "Carter's Grove Brown", number: "CW-15", hex: "#9A6848", collection: "Williamsburg" },
  { name: "Powell Buff", number: "CW-20", hex: "#D4BC80", collection: "Williamsburg" },
  { name: "Market Square Gold", number: "CW-25", hex: "#C8A840", collection: "Williamsburg" },
  { name: "Raleigh Tavern Gold", number: "CW-30", hex: "#C0A030", collection: "Williamsburg" },
  { name: "Nursery Green", number: "CW-35", hex: "#9AB88A", collection: "Williamsburg" },
  { name: "Wythe Blue", number: "CW-40", hex: "#6C8FA8", collection: "Williamsburg" },
  { name: "Natural Linen", number: "CW-45", hex: "#D8CBA8", collection: "Williamsburg" },
  { name: "North Garden Gold", number: "CW-50", hex: "#BCA050", collection: "Williamsburg" },
  { name: "Williamsburg Linen", number: "CW-55", hex: "#DAD0B8", collection: "Williamsburg" },
  { name: "Courthouse Colonial Green", number: "CW-60", hex: "#4E6840", collection: "Williamsburg" },
  { name: "Randolph Gold", number: "CW-65", hex: "#C09840", collection: "Williamsburg" },
  { name: "Tobacco Road", number: "CW-70", hex: "#8A7050", collection: "Williamsburg" },
  { name: "Williamsburg Brown", number: "CW-75", hex: "#6E4C2E", collection: "Williamsburg" },
  { name: "Craig Blue", number: "CW-80", hex: "#7890A0", collection: "Williamsburg" },
  { name: "Cellar Door Gray", number: "CW-85", hex: "#7C8080", collection: "Williamsburg" },
  { name: "Gravel Lane", number: "CW-90", hex: "#9A9A90", collection: "Williamsburg" },
  { name: "Raleigh Tavern Blue", number: "CW-95", hex: "#6080A0", collection: "Williamsburg" },
  { name: "Wren's Nest", number: "CW-100", hex: "#9A8060", collection: "Williamsburg" },
  { name: "Carter's Grove", number: "CW-110", hex: "#906848", collection: "Williamsburg" },
  { name: "Coffeehouse Tan", number: "CW-125", hex: "#B89870", collection: "Williamsburg" },
  { name: "Courtyard", number: "CW-130", hex: "#B0A878", collection: "Williamsburg" },
  { name: "Palace Arms Sage", number: "CW-135", hex: "#A0A878", collection: "Williamsburg" },
  { name: "Natural Bridge", number: "CW-150", hex: "#C8B888", collection: "Williamsburg" },
  { name: "Chowning's Tavern Tan", number: "CW-155", hex: "#C0B080", collection: "Williamsburg" },
  { name: "Courthouse Green", number: "CW-165", hex: "#607858", collection: "Williamsburg" },
  { name: "Colonial Blue", number: "CW-180", hex: "#506880", collection: "Williamsburg" },
  { name: "Bruton Parish", number: "CW-185", hex: "#485870", collection: "Williamsburg" },
  { name: "Historic Burgundy", number: "CW-220", hex: "#7A3038", collection: "Williamsburg" },
  { name: "Autumn Red", number: "CW-225", hex: "#9A4038", collection: "Williamsburg" },
  { name: "Oxblood Red", number: "CW-230", hex: "#6A2828", collection: "Williamsburg" },
];

// ── COLOR STORIES / CLASSICS (2000-series) ────────────────────────────────────
const classicsColors: BenjaminMooreColor[] = [
  // Reds & Pinks
  { name: "Dark Garnet", number: "2000-10", hex: "#5E1C1C", collection: "Color Stories" },
  { name: "Pomegranate Juice", number: "2000-20", hex: "#7A2020", collection: "Color Stories" },
  { name: "Rockport Rose", number: "2000-30", hex: "#A83434", collection: "Color Stories" },
  { name: "Hibiscus", number: "2000-40", hex: "#C44848", collection: "Color Stories" },
  { name: "Raspberry Sherbet", number: "2000-50", hex: "#D85F5F", collection: "Color Stories" },
  { name: "Peach Brandy", number: "2000-60", hex: "#E89090", collection: "Color Stories" },
  { name: "Cabernet", number: "2083-10", hex: "#6A1E2E", collection: "Color Stories" },
  { name: "Burgundy", number: "2083-20", hex: "#7A2040", collection: "Color Stories" },
  { name: "Eggplant", number: "2084-10", hex: "#4A1A30", collection: "Color Stories" },
  { name: "Wineberry", number: "2084-20", hex: "#622040", collection: "Color Stories" },
  { name: "Red Parrot", number: "2088-10", hex: "#8B1A1A", collection: "Color Stories" },
  { name: "Dinner Party", number: "2088-20", hex: "#A02020", collection: "Color Stories" },
  { name: "Tomato Red", number: "2086-20", hex: "#C03428", collection: "Color Stories" },
  { name: "Brick Red", number: "2089-30", hex: "#A84038", collection: "Color Stories" },
  { name: "Heritage Red", number: "PM-18", hex: "#943030", collection: "Color Stories" },
  { name: "Caliente", number: "2090-10", hex: "#7E1A1A", collection: "Color Stories" },
  { name: "Barn Red", number: "2169-20", hex: "#8A2828", collection: "Color Stories" },
  // Oranges & Terracottas
  { name: "Jack-O-Lantern", number: "2156-20", hex: "#E06A1A", collection: "Color Stories" },
  { name: "Tropical Orange", number: "2092-30", hex: "#D05020", collection: "Color Stories" },
  { name: "Rust", number: "2093-30", hex: "#B64820", collection: "Color Stories" },
  { name: "Papaya", number: "2094-40", hex: "#E07C48", collection: "Color Stories" },
  { name: "Burnt Sienna", number: "2098-10", hex: "#7A3520", collection: "Color Stories" },
  { name: "Cedar", number: "2171-30", hex: "#B05A38", collection: "Color Stories" },
  { name: "Terra Cotta", number: "1202", hex: "#C26A44", collection: "Color Stories" },
  { name: "Coral", number: "2170-40", hex: "#E8836A", collection: "Color Stories" },
  { name: "Caramelized", number: "2160-20", hex: "#A06030", collection: "Color Stories" },
  // Yellows
  { name: "Mustard Seed", number: "2154-30", hex: "#B89040", collection: "Color Stories" },
  { name: "Buttered Corn", number: "2154-40", hex: "#D4B858", collection: "Color Stories" },
  { name: "Golden Straw", number: "2152-50", hex: "#D4B068", collection: "Color Stories" },
  { name: "Pale Straw", number: "2153-60", hex: "#E2CEAC", collection: "Color Stories" },
  { name: "Harvest Moon", number: "163", hex: "#C49A28", collection: "Color Stories" },
  { name: "Gold Finch", number: "297", hex: "#DDB840", collection: "Color Stories" },
  { name: "Pineapple", number: "165", hex: "#C89230", collection: "Color Stories" },
  { name: "Lemon Sorbet", number: "2019-50", hex: "#EDD06C", collection: "Color Stories" },
  { name: "Desert Tan", number: "2153-40", hex: "#C8A870", collection: "Color Stories" },
  { name: "Dijon", number: "2158-30", hex: "#C0A040", collection: "Color Stories" },
  // Greens
  { name: "Forest Green", number: "2047-10", hex: "#3B5244", collection: "Color Stories" },
  { name: "Jade Garden", number: "2047-30", hex: "#567761", collection: "Color Stories" },
  { name: "Nile Green", number: "2035-40", hex: "#7F9E82", collection: "Color Stories" },
  { name: "October Mist", number: "1495", hex: "#B4C2AD", collection: "Color Stories" },
  { name: "Fernwood", number: "2144-40", hex: "#9BA882", collection: "Color Stories" },
  { name: "Hunter Green", number: "2150-10", hex: "#1E3020", collection: "Color Stories" },
  { name: "Evergreen", number: "2150-30", hex: "#3A5A40", collection: "Color Stories" },
  { name: "Jade", number: "2150-40", hex: "#4A6E50", collection: "Color Stories" },
  { name: "Fern", number: "2150-50", hex: "#7A9C78", collection: "Color Stories" },
  { name: "Thyme", number: "2145-20", hex: "#4E5E40", collection: "Color Stories" },
  { name: "Avocado", number: "2145-30", hex: "#6A7850", collection: "Color Stories" },
  { name: "Sage Green", number: "2143-40", hex: "#8AA082", collection: "Color Stories" },
  // Blues
  { name: "Old Navy", number: "2063-10", hex: "#213A53", collection: "Color Stories" },
  { name: "Patriot Blue", number: "2064-20", hex: "#2E4A6B", collection: "Color Stories" },
  { name: "Slate Blue", number: "2062-40", hex: "#5C7E9C", collection: "Color Stories" },
  { name: "Harbor Gray", number: "2136-50", hex: "#9AABB7", collection: "Color Stories" },
  { name: "Iceberg", number: "2057-60", hex: "#A2BDD0", collection: "Color Stories" },
  { name: "Breath of Fresh Air", number: "806", hex: "#C8DBE5", collection: "Color Stories" },
  { name: "Beach Glass", number: "1564", hex: "#9BC8CC", collection: "Color Stories" },
  { name: "Admiral Blue", number: "2062-30", hex: "#2A5298", collection: "Color Stories" },
  { name: "Deep Royal Blue", number: "2062-20", hex: "#234070", collection: "Color Stories" },
  { name: "Midnight Blue", number: "2062-10", hex: "#1C2844", collection: "Color Stories" },
  { name: "Crystal Blue", number: "2062-50", hex: "#8AAFCC", collection: "Color Stories" },
  { name: "Bunker Hill Blue", number: "2133-30", hex: "#4A6878", collection: "Color Stories" },
  { name: "Brittany Blue", number: "2135-40", hex: "#4A6070", collection: "Color Stories" },
  { name: "Federal Blue", number: "2130-40", hex: "#3E5878", collection: "Color Stories" },
  // Grays
  { name: "Wrought Iron", number: "2124-10", hex: "#474B4E", collection: "Color Stories" },
  { name: "Gray Owl", number: "2137-60", hex: "#D3D4CC", collection: "Color Stories" },
  { name: "Silver Mink", number: "2111-40", hex: "#B0A99E", collection: "Color Stories" },
  { name: "Nimbus", number: "2131-50", hex: "#BCBDB5", collection: "Color Stories" },
  { name: "Fossil Gray", number: "2108-40", hex: "#9A9489", collection: "Color Stories" },
  { name: "Seal Gray", number: "2119-55", hex: "#767973", collection: "Color Stories" },
  { name: "Abalone", number: "2108-60", hex: "#D3CFC7", collection: "Color Stories" },
  { name: "Driftwood", number: "2108-30", hex: "#7A7068", collection: "Color Stories" },
  { name: "Amherst Gray", number: "2110-30", hex: "#786E62", collection: "Color Stories" },
  { name: "Charcoal", number: "2117-20", hex: "#2E2E2C", collection: "Color Stories" },
  { name: "Graphite", number: "2119-40", hex: "#50504C", collection: "Color Stories" },
  { name: "Black", number: "2132-10", hex: "#1E1E1E", collection: "Color Stories" },
  { name: "Near Black", number: "2119-20", hex: "#252424", collection: "Color Stories" },
  // Browns & Taupes
  { name: "Chocolate Sundae", number: "2107-20", hex: "#5A3A28", collection: "Color Stories" },
  { name: "Dark Walnut", number: "2100-20", hex: "#6A4A30", collection: "Color Stories" },
  { name: "Milk Chocolate", number: "2100-30", hex: "#8A5C3E", collection: "Color Stories" },
  { name: "Caramel", number: "2100-40", hex: "#B07848", collection: "Color Stories" },
  { name: "Potting Soil", number: "2107-30", hex: "#7A5238", collection: "Color Stories" },
  { name: "Rustic Tan", number: "2116-30", hex: "#9A8870", collection: "Color Stories" },
  { name: "Sandy Brown", number: "2162-40", hex: "#C8A870", collection: "Color Stories" },
  { name: "Grayish Beige", number: "OC-38", hex: "#C4B8A8", collection: "Color Stories" },
  { name: "Pale Straw Tan", number: "2153-50", hex: "#D8C090", collection: "Color Stories" },
  // Purples & Mauves
  { name: "Dewberry", number: "2070-30", hex: "#7A5870", collection: "Color Stories" },
  { name: "Victorian Gardens", number: "2071-30", hex: "#6A4E6A", collection: "Color Stories" },
  { name: "Smoky Lilac", number: "2073-50", hex: "#B0A0B8", collection: "Color Stories" },
  { name: "Lavender Mist", number: "2069-60", hex: "#CBBFCD", collection: "Color Stories" },
  { name: "Romantic Pink", number: "2075-50", hex: "#E0A8B8", collection: "Color Stories" },
  // Additional 2000-series
  { name: "Black Mocha", number: "2125-10", hex: "#2E2420", collection: "Color Stories" },
  { name: "Espresso", number: "2126-10", hex: "#321E18", collection: "Color Stories" },
  { name: "Iron", number: "2119-30", hex: "#383630", collection: "Color Stories" },
  { name: "Mountain Goat", number: "2119-40", hex: "#707068", collection: "Color Stories" },
  { name: "Hale Navy Alt", number: "2135-30", hex: "#324858", collection: "Color Stories" },
  { name: "Dusty Miller Blue", number: "2132-30", hex: "#8A9898", collection: "Color Stories" },
  { name: "Night Blue", number: "2129-10", hex: "#1A2030", collection: "Color Stories" },
  { name: "Deep Blue", number: "2129-40", hex: "#2A4870", collection: "Color Stories" },
  { name: "Ice Storm", number: "2128-30", hex: "#C8D4E0", collection: "Color Stories" },
  { name: "Aganthus Green", number: "2134-30", hex: "#4A6858", collection: "Color Stories" },
  { name: "Forged Iron", number: "2135-10", hex: "#2A2E2E", collection: "Color Stories" },
  { name: "Sea Salt Gray", number: "2143-40", hex: "#C4C8C0", collection: "Color Stories" },
  { name: "Dark Olive", number: "2149-10", hex: "#2E3020", collection: "Color Stories" },
  { name: "Lime White", number: "2151-40", hex: "#C8C88C", collection: "Color Stories" },
  { name: "Warm Stone", number: "2116-30", hex: "#9A8870", collection: "Color Stories" },
  { name: "Carbon Copy", number: "2141-10", hex: "#2A2828", collection: "Color Stories" },
  { name: "Soot", number: "2139-10", hex: "#2C2C28", collection: "Color Stories" },
  { name: "Royal Navy", number: "2140-30", hex: "#1E3050", collection: "Color Stories" },
  { name: "Sable", number: "2145-10", hex: "#2A2018", collection: "Color Stories" },
  { name: "Deep Maroon", number: "2082-10", hex: "#5C1C28", collection: "Color Stories" },
  { name: "Black Cherry", number: "2085-10", hex: "#3A1420", collection: "Color Stories" },
  { name: "Dark Red", number: "2086-10", hex: "#8A1E10", collection: "Color Stories" },
  { name: "Red", number: "2087-10", hex: "#A01C18", collection: "Color Stories" },
  { name: "Nantucket Red", number: "2167-30", hex: "#C04040", collection: "Color Stories" },
  { name: "Holiday Red", number: "2166-20", hex: "#C02828", collection: "Color Stories" },
  { name: "Adobe", number: "2163-20", hex: "#A87050", collection: "Color Stories" },
  { name: "Clay", number: "2094-30", hex: "#B06040", collection: "Color Stories" },
];

// ── COLOR PREVIEW SERIES (CSP) ────────────────────────────────────────────────
const colorPreviewColors: BenjaminMooreColor[] = [
  { name: "Wind Chime", number: "CSP-5", hex: "#E8E4DA", collection: "Color Preview" },
  { name: "Winter Orchard", number: "CSP-10", hex: "#EDE8D8", collection: "Color Preview" },
  { name: "Vapor Trails", number: "CSP-15", hex: "#E4E0D2", collection: "Color Preview" },
  { name: "Shoji White", number: "CSP-20", hex: "#E0DBD0", collection: "Color Preview" },
  { name: "Pismo Dunes", number: "CSP-25", hex: "#D8D0BF", collection: "Color Preview" },
  { name: "Camelback", number: "CSP-30", hex: "#D4C8AC", collection: "Color Preview" },
  { name: "Sandy Cove", number: "CSP-35", hex: "#CDBFA0", collection: "Color Preview" },
  { name: "Bamboo Grove", number: "CSP-40", hex: "#C4B58A", collection: "Color Preview" },
  { name: "Antique Candle", number: "CSP-45", hex: "#C0A870", collection: "Color Preview" },
  { name: "Mellow Yellow", number: "CSP-50", hex: "#E0C85C", collection: "Color Preview" },
  { name: "Sun Kissed", number: "CSP-55", hex: "#D4B84C", collection: "Color Preview" },
  { name: "Cactus Garden", number: "CSP-60", hex: "#A0A858", collection: "Color Preview" },
  { name: "Garden Oasis", number: "CSP-65", hex: "#8AAA78", collection: "Color Preview" },
  { name: "Forest Walk", number: "CSP-70", hex: "#607850", collection: "Color Preview" },
  { name: "Sage Garden", number: "CSP-75", hex: "#9AB095", collection: "Color Preview" },
  { name: "Sea Breeze", number: "CSP-80", hex: "#A0C0C0", collection: "Color Preview" },
  { name: "Coastal Blue", number: "CSP-85", hex: "#7899AB", collection: "Color Preview" },
  { name: "Harbor Blue", number: "CSP-90", hex: "#5878A0", collection: "Color Preview" },
  { name: "Midnight Sea", number: "CSP-95", hex: "#304870", collection: "Color Preview" },
  { name: "Storm Blue", number: "CSP-100", hex: "#4A6878", collection: "Color Preview" },
  { name: "Dusty Blue", number: "CSP-105", hex: "#8090A8", collection: "Color Preview" },
  { name: "Lilac Haze", number: "CSP-110", hex: "#B0A8C0", collection: "Color Preview" },
  { name: "Grape Fizz", number: "CSP-115", hex: "#887898", collection: "Color Preview" },
  { name: "Mauve", number: "CSP-120", hex: "#C0A0B0", collection: "Color Preview" },
  { name: "Rose Blush", number: "CSP-125", hex: "#D4B0B8", collection: "Color Preview" },
  { name: "Faded Brick", number: "CSP-130", hex: "#C08880", collection: "Color Preview" },
  { name: "Dusty Rose", number: "CSP-135", hex: "#D0A8A0", collection: "Color Preview" },
  { name: "Pale Pink", number: "CSP-140", hex: "#F0D0C8", collection: "Color Preview" },
  { name: "Blush Pink", number: "CSP-145", hex: "#F0C0B8", collection: "Color Preview" },
  { name: "Coral Blush", number: "CSP-150", hex: "#E8A898", collection: "Color Preview" },
  { name: "Warm White", number: "CSP-155", hex: "#F4F0E4", collection: "Color Preview" },
  { name: "Parchment", number: "CSP-160", hex: "#EDE4C8", collection: "Color Preview" },
  { name: "Aged Paper", number: "CSP-165", hex: "#E4D8B8", collection: "Color Preview" },
  { name: "Antique Gold", number: "CSP-170", hex: "#C8A858", collection: "Color Preview" },
  { name: "Warm Caramel", number: "CSP-175", hex: "#C09060", collection: "Color Preview" },
  { name: "Russet", number: "CSP-180", hex: "#A86840", collection: "Color Preview" },
  { name: "Autumn Spice", number: "CSP-185", hex: "#B06838", collection: "Color Preview" },
  { name: "Terracotta Haze", number: "CSP-190", hex: "#C07858", collection: "Color Preview" },
  { name: "Copper Tone", number: "CSP-195", hex: "#B07050", collection: "Color Preview" },
  { name: "Warm Gray", number: "CSP-200", hex: "#B8B4AE", collection: "Color Preview" },
  { name: "Steel Gray", number: "CSP-205", hex: "#9898A0", collection: "Color Preview" },
  { name: "Slate Stone", number: "CSP-210", hex: "#787880", collection: "Color Preview" },
  { name: "Dark Charcoal", number: "CSP-215", hex: "#4A4A48", collection: "Color Preview" },
  { name: "Smoky Black", number: "CSP-220", hex: "#302E2C", collection: "Color Preview" },
];

// ── ALL COLORS ────────────────────────────────────────────────────────────────
export const ALL_COLORS: BenjaminMooreColor[] = [
  ...affinityColors,
  ...americasColors,
  ...historicalColors,
  ...offWhiteColors,
  ...williamsburgColors,
  ...classicsColors,
  ...colorPreviewColors,
];

// ── COLLECTION NAMES ──────────────────────────────────────────────────────────
export const COLLECTIONS = [
  "All",
  "Historical Colors",
  "Off-Whites",
  "Williamsburg",
  "Affinity",
  "Color Stories",
  "Americas Colors",
  "Color Preview",
] as const;

export type CollectionName = (typeof COLLECTIONS)[number];

export function getColorsByCollection(collection: string): BenjaminMooreColor[] {
  if (collection === "All") return ALL_COLORS;
  return ALL_COLORS.filter((c) => c.collection === collection);
}

// ── BACKWARDS-COMPATIBILITY ──────────────────────────────────────────────────
// The old interface used `category` — keep these for any code that references it

export type ColorCategory =
  | "Whites & Off-Whites"
  | "Grays"
  | "Blues"
  | "Greens"
  | "Reds & Oranges"
  | "Yellows & Neutrals"
  | "Browns & Taupes";

export const colorCategories: ColorCategory[] = [
  "Whites & Off-Whites",
  "Grays",
  "Blues",
  "Greens",
  "Reds & Oranges",
  "Yellows & Neutrals",
  "Browns & Taupes",
];

// Legacy alias
export const bmColors = ALL_COLORS;

export function getColorsByCategory(category: ColorCategory): BenjaminMooreColor[] {
  const map: Record<ColorCategory, (c: BenjaminMooreColor) => boolean> = {
    "Whites & Off-Whites": (c) =>
      c.collection === "Off-Whites" || /white|cream|ivory|linen|snow/i.test(c.name),
    Grays: (c) =>
      /gray|grey|pewter|charcoal|slate|iron|graphite|ash/i.test(c.name),
    Blues: (c) =>
      /blue|navy|aqua|teal|cyan|indigo|cobalt|buxton|hale/i.test(c.name),
    Greens: (c) =>
      /green|sage|olive|fern|moss|forest|emerald|jade/i.test(c.name),
    "Reds & Oranges": (c) =>
      /red|orange|coral|rose|crimson|burgundy|terracotta|cedar|brick|rust/i.test(c.name),
    "Yellows & Neutrals": (c) =>
      /yellow|gold|mustard|straw|corn|honey|butter|lemon|citrine/i.test(c.name),
    "Browns & Taupes": (c) =>
      /brown|taupe|tan|beige|chocolate|walnut|mocha|caramel|sienna/i.test(c.name),
  };
  return ALL_COLORS.filter(map[category]);
}

export function getColorByHex(hex: string): BenjaminMooreColor | undefined {
  return ALL_COLORS.find((c) => c.hex.toLowerCase() === hex.toLowerCase());
}

export function getColorByNumber(number: string): BenjaminMooreColor | undefined {
  return ALL_COLORS.find((c) => c.number === number);
}
